//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET.BUSINESS.DAL.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class METEntities : DbContext
    {
        public METEntities()
            : base("name=METEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_ASSIGNMENTS> T_ASSIGNMENTS { get; set; }
        public virtual DbSet<T_COMPONENT> T_COMPONENT { get; set; }
        public virtual DbSet<T_CONFIG> T_CONFIG { get; set; }
        public virtual DbSet<T_CONFIG_DETAIL> T_CONFIG_DETAIL { get; set; }
        public virtual DbSet<T_REFERENCE> T_REFERENCE { get; set; }
        public virtual DbSet<T_RELEASE> T_RELEASE { get; set; }
        public virtual DbSet<T_SPRINT> T_SPRINT { get; set; }
        public virtual DbSet<T_SYSTEM> T_SYSTEM { get; set; }
        public virtual DbSet<T_USERS> T_USERS { get; set; }
        public virtual DbSet<T_WORK_COMPONENT> T_WORK_COMPONENT { get; set; }
        public virtual DbSet<T_WORK_ITEM> T_WORK_ITEM { get; set; }
        public virtual DbSet<T_ASSIGNMENTS_HIST> T_ASSIGNMENTS_HIST { get; set; }
        public virtual DbSet<T_RELEASE_USER_ACCESS> T_RELEASE_USER_ACCESS { get; set; }
        public virtual DbSet<T_SPRINT_USER_ACCESS> T_SPRINT_USER_ACCESS { get; set; }
    
        public virtual ObjectResult<USP_RELEASE_GET_USER_LIST_Result> USP_RELEASE_GET_USER_LIST(Nullable<int> p_ReleaseSeqId)
        {
            var p_ReleaseSeqIdParameter = p_ReleaseSeqId.HasValue ?
                new ObjectParameter("p_ReleaseSeqId", p_ReleaseSeqId) :
                new ObjectParameter("p_ReleaseSeqId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RELEASE_GET_USER_LIST_Result>("USP_RELEASE_GET_USER_LIST", p_ReleaseSeqIdParameter);
        }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<string> USP_ASSIGNMENT_GET_ALL_STATUSES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_ASSIGNMENT_GET_ALL_STATUSES");
        }
    
        public virtual ObjectResult<USP_ASSIGNMENT_GET_CURRENT_Result> USP_ASSIGNMENT_GET_CURRENT(Nullable<long> p_workItemID)
        {
            var p_workItemIDParameter = p_workItemID.HasValue ?
                new ObjectParameter("p_workItemID", p_workItemID) :
                new ObjectParameter("p_workItemID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ASSIGNMENT_GET_CURRENT_Result>("USP_ASSIGNMENT_GET_CURRENT", p_workItemIDParameter);
        }
    
        public virtual ObjectResult<USP_ASSIGNMENT_GET_HISTORY_Result> USP_ASSIGNMENT_GET_HISTORY(Nullable<int> p_workItemID)
        {
            var p_workItemIDParameter = p_workItemID.HasValue ?
                new ObjectParameter("p_workItemID", p_workItemID) :
                new ObjectParameter("p_workItemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_ASSIGNMENT_GET_HISTORY_Result>("USP_ASSIGNMENT_GET_HISTORY", p_workItemIDParameter);
        }
    
        public virtual int USP_ASSIGNMENT_SAVE_DETAILS(Nullable<long> p_ItemID, Nullable<long> p_userID, Nullable<long> p_status, string p_comments, string p_updtd_by, string p_duedate)
        {
            var p_ItemIDParameter = p_ItemID.HasValue ?
                new ObjectParameter("p_ItemID", p_ItemID) :
                new ObjectParameter("p_ItemID", typeof(long));
    
            var p_userIDParameter = p_userID.HasValue ?
                new ObjectParameter("p_userID", p_userID) :
                new ObjectParameter("p_userID", typeof(long));
    
            var p_statusParameter = p_status.HasValue ?
                new ObjectParameter("p_status", p_status) :
                new ObjectParameter("p_status", typeof(long));
    
            var p_commentsParameter = p_comments != null ?
                new ObjectParameter("p_comments", p_comments) :
                new ObjectParameter("p_comments", typeof(string));
    
            var p_updtd_byParameter = p_updtd_by != null ?
                new ObjectParameter("p_updtd_by", p_updtd_by) :
                new ObjectParameter("p_updtd_by", typeof(string));
    
            var p_duedateParameter = p_duedate != null ?
                new ObjectParameter("p_duedate", p_duedate) :
                new ObjectParameter("p_duedate", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_ASSIGNMENT_SAVE_DETAILS", p_ItemIDParameter, p_userIDParameter, p_statusParameter, p_commentsParameter, p_updtd_byParameter, p_duedateParameter);
        }
    
        public virtual int USP_CLEAR_COMPONENT_CONFIG(Nullable<int> systemID)
        {
            var systemIDParameter = systemID.HasValue ?
                new ObjectParameter("systemID", systemID) :
                new ObjectParameter("systemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_CLEAR_COMPONENT_CONFIG", systemIDParameter);
        }
    
        public virtual int USP_COMPONENT_CONFIG_SAVE(Nullable<int> systemID, Nullable<int> p_complexity, Nullable<int> p_type, Nullable<double> p_weight)
        {
            var systemIDParameter = systemID.HasValue ?
                new ObjectParameter("systemID", systemID) :
                new ObjectParameter("systemID", typeof(int));
    
            var p_complexityParameter = p_complexity.HasValue ?
                new ObjectParameter("p_complexity", p_complexity) :
                new ObjectParameter("p_complexity", typeof(int));
    
            var p_typeParameter = p_type.HasValue ?
                new ObjectParameter("p_type", p_type) :
                new ObjectParameter("p_type", typeof(int));
    
            var p_weightParameter = p_weight.HasValue ?
                new ObjectParameter("p_weight", p_weight) :
                new ObjectParameter("p_weight", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_COMPONENT_CONFIG_SAVE", systemIDParameter, p_complexityParameter, p_typeParameter, p_weightParameter);
        }
    
        public virtual int USP_DELETE_ITEM_COMPONENT(Nullable<long> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_DELETE_ITEM_COMPONENT", idParameter);
        }
    
        public virtual ObjectResult<USP_GET_COMP_COMPLX_REF_Result> USP_GET_COMP_COMPLX_REF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_COMP_COMPLX_REF_Result>("USP_GET_COMP_COMPLX_REF");
        }
    
        public virtual ObjectResult<USP_GET_COMP_TYPE_REF_Result> USP_GET_COMP_TYPE_REF()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_COMP_TYPE_REF_Result>("USP_GET_COMP_TYPE_REF");
        }
    
        public virtual ObjectResult<USP_GET_COMPONENTS_FOR_ITEM_Result> USP_GET_COMPONENTS_FOR_ITEM(Nullable<int> id, Nullable<int> compType)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var compTypeParameter = compType.HasValue ?
                new ObjectParameter("compType", compType) :
                new ObjectParameter("compType", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_COMPONENTS_FOR_ITEM_Result>("USP_GET_COMPONENTS_FOR_ITEM", idParameter, compTypeParameter);
        }
    
        public virtual ObjectResult<USP_GET_CONFIG_VALUES_Result> USP_GET_CONFIG_VALUES(Nullable<int> p_SystemID, string p_GroupCde)
        {
            var p_SystemIDParameter = p_SystemID.HasValue ?
                new ObjectParameter("p_SystemID", p_SystemID) :
                new ObjectParameter("p_SystemID", typeof(int));
    
            var p_GroupCdeParameter = p_GroupCde != null ?
                new ObjectParameter("p_GroupCde", p_GroupCde) :
                new ObjectParameter("p_GroupCde", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_CONFIG_VALUES_Result>("USP_GET_CONFIG_VALUES", p_SystemIDParameter, p_GroupCdeParameter);
        }
    
        public virtual ObjectResult<USP_GET_ITEM_COMPONENTS_Result> USP_GET_ITEM_COMPONENTS(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_ITEM_COMPONENTS_Result>("USP_GET_ITEM_COMPONENTS", idParameter);
        }
    
        public virtual ObjectResult<USP_GET_WORK_ITEM_Result> USP_GET_WORK_ITEM(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GET_WORK_ITEM_Result>("USP_GET_WORK_ITEM", idParameter);
        }
    
        public virtual int USP_INSERT_ITEM_COMPONENTS(Nullable<long> work_item_id, string name, Nullable<long> complexity, Nullable<long> type)
        {
            var work_item_idParameter = work_item_id.HasValue ?
                new ObjectParameter("work_item_id", work_item_id) :
                new ObjectParameter("work_item_id", typeof(long));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var complexityParameter = complexity.HasValue ?
                new ObjectParameter("complexity", complexity) :
                new ObjectParameter("complexity", typeof(long));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERT_ITEM_COMPONENTS", work_item_idParameter, nameParameter, complexityParameter, typeParameter);
        }
    
        public virtual int USP_INSERT_WORK_ITEM(Nullable<int> tfs_id, string title, string type, string severity, Nullable<int> systemSeq)
        {
            var tfs_idParameter = tfs_id.HasValue ?
                new ObjectParameter("tfs_id", tfs_id) :
                new ObjectParameter("tfs_id", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var typeParameter = type != null ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(string));
    
            var severityParameter = severity != null ?
                new ObjectParameter("severity", severity) :
                new ObjectParameter("severity", typeof(string));
    
            var systemSeqParameter = systemSeq.HasValue ?
                new ObjectParameter("systemSeq", systemSeq) :
                new ObjectParameter("systemSeq", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_INSERT_WORK_ITEM", tfs_idParameter, titleParameter, typeParameter, severityParameter, systemSeqParameter);
        }
    
        public virtual ObjectResult<USP_LANDING_GET_NON_TFS_RELEASE_LIST_Result> USP_LANDING_GET_NON_TFS_RELEASE_LIST(string p_systemTfsGuid)
        {
            var p_systemTfsGuidParameter = p_systemTfsGuid != null ?
                new ObjectParameter("p_systemTfsGuid", p_systemTfsGuid) :
                new ObjectParameter("p_systemTfsGuid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_LANDING_GET_NON_TFS_RELEASE_LIST_Result>("USP_LANDING_GET_NON_TFS_RELEASE_LIST", p_systemTfsGuidParameter);
        }
    
        public virtual ObjectResult<USP_LANDING_GET_RELEASE_LIST_Result> USP_LANDING_GET_RELEASE_LIST(Nullable<int> p_SystemID)
        {
            var p_SystemIDParameter = p_SystemID.HasValue ?
                new ObjectParameter("p_SystemID", p_SystemID) :
                new ObjectParameter("p_SystemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_LANDING_GET_RELEASE_LIST_Result>("USP_LANDING_GET_RELEASE_LIST", p_SystemIDParameter);
        }
    
        public virtual ObjectResult<USP_LANDING_GET_SYSTEM_LIST_Result> USP_LANDING_GET_SYSTEM_LIST()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_LANDING_GET_SYSTEM_LIST_Result>("USP_LANDING_GET_SYSTEM_LIST");
        }
    
        public virtual ObjectResult<USP_LANDING_SEARCH_RELEASE_Result> USP_LANDING_SEARCH_RELEASE(Nullable<int> p_SysSeq, string p_ReleaseName, Nullable<int> p_ReleaseTfsId)
        {
            var p_SysSeqParameter = p_SysSeq.HasValue ?
                new ObjectParameter("p_SysSeq", p_SysSeq) :
                new ObjectParameter("p_SysSeq", typeof(int));
    
            var p_ReleaseNameParameter = p_ReleaseName != null ?
                new ObjectParameter("p_ReleaseName", p_ReleaseName) :
                new ObjectParameter("p_ReleaseName", typeof(string));
    
            var p_ReleaseTfsIdParameter = p_ReleaseTfsId.HasValue ?
                new ObjectParameter("p_ReleaseTfsId", p_ReleaseTfsId) :
                new ObjectParameter("p_ReleaseTfsId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_LANDING_SEARCH_RELEASE_Result>("USP_LANDING_SEARCH_RELEASE", p_SysSeqParameter, p_ReleaseNameParameter, p_ReleaseTfsIdParameter);
        }
    
        public virtual ObjectResult<USP_LANDING_SEARCH_SYSTEM_Result> USP_LANDING_SEARCH_SYSTEM(string p_SysName, string p_TfsGuid)
        {
            var p_SysNameParameter = p_SysName != null ?
                new ObjectParameter("p_SysName", p_SysName) :
                new ObjectParameter("p_SysName", typeof(string));
    
            var p_TfsGuidParameter = p_TfsGuid != null ?
                new ObjectParameter("p_TfsGuid", p_TfsGuid) :
                new ObjectParameter("p_TfsGuid", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_LANDING_SEARCH_SYSTEM_Result>("USP_LANDING_SEARCH_SYSTEM", p_SysNameParameter, p_TfsGuidParameter);
        }
    
        public virtual int USP_RELEASE_DELETE_WORK_ITEM(Nullable<int> p_WorkItemID)
        {
            var p_WorkItemIDParameter = p_WorkItemID.HasValue ?
                new ObjectParameter("p_WorkItemID", p_WorkItemID) :
                new ObjectParameter("p_WorkItemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_RELEASE_DELETE_WORK_ITEM", p_WorkItemIDParameter);
        }
    
        public virtual ObjectResult<USP_RELEASE_GENERATE_REPORT_Result> USP_RELEASE_GENERATE_REPORT(Nullable<int> p_ReleaseId)
        {
            var p_ReleaseIdParameter = p_ReleaseId.HasValue ?
                new ObjectParameter("p_ReleaseId", p_ReleaseId) :
                new ObjectParameter("p_ReleaseId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RELEASE_GENERATE_REPORT_Result>("USP_RELEASE_GENERATE_REPORT", p_ReleaseIdParameter);
        }
    
        public virtual ObjectResult<USP_RELEASE_GET_ATTRIBUTE_LIST_Result> USP_RELEASE_GET_ATTRIBUTE_LIST(Nullable<int> p_ReleaseSeqID)
        {
            var p_ReleaseSeqIDParameter = p_ReleaseSeqID.HasValue ?
                new ObjectParameter("p_ReleaseSeqID", p_ReleaseSeqID) :
                new ObjectParameter("p_ReleaseSeqID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RELEASE_GET_ATTRIBUTE_LIST_Result>("USP_RELEASE_GET_ATTRIBUTE_LIST", p_ReleaseSeqIDParameter);
        }
    
        public virtual ObjectResult<USP_RELEASE_GET_RELEASE_META_Result> USP_RELEASE_GET_RELEASE_META(Nullable<int> p_ReleaseSeqID)
        {
            var p_ReleaseSeqIDParameter = p_ReleaseSeqID.HasValue ?
                new ObjectParameter("p_ReleaseSeqID", p_ReleaseSeqID) :
                new ObjectParameter("p_ReleaseSeqID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RELEASE_GET_RELEASE_META_Result>("USP_RELEASE_GET_RELEASE_META", p_ReleaseSeqIDParameter);
        }
    
        public virtual ObjectResult<USP_RELEASE_GET_WORK_ITEM_COMPONENT_Result> USP_RELEASE_GET_WORK_ITEM_COMPONENT(Nullable<int> p_WorkItemID)
        {
            var p_WorkItemIDParameter = p_WorkItemID.HasValue ?
                new ObjectParameter("p_WorkItemID", p_WorkItemID) :
                new ObjectParameter("p_WorkItemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RELEASE_GET_WORK_ITEM_COMPONENT_Result>("USP_RELEASE_GET_WORK_ITEM_COMPONENT", p_WorkItemIDParameter);
        }
    
        public virtual ObjectResult<USP_RELEASE_GET_WORK_ITEM_LIST_Result> USP_RELEASE_GET_WORK_ITEM_LIST(Nullable<int> p_ReleaseSeqID)
        {
            var p_ReleaseSeqIDParameter = p_ReleaseSeqID.HasValue ?
                new ObjectParameter("p_ReleaseSeqID", p_ReleaseSeqID) :
                new ObjectParameter("p_ReleaseSeqID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_RELEASE_GET_WORK_ITEM_LIST_Result>("USP_RELEASE_GET_WORK_ITEM_LIST", p_ReleaseSeqIDParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> USP_RELEASE_SAVE_NON_TFS(Nullable<int> p_SystemSeqId, string p_ReleaseTitle)
        {
            var p_SystemSeqIdParameter = p_SystemSeqId.HasValue ?
                new ObjectParameter("p_SystemSeqId", p_SystemSeqId) :
                new ObjectParameter("p_SystemSeqId", typeof(int));
    
            var p_ReleaseTitleParameter = p_ReleaseTitle != null ?
                new ObjectParameter("p_ReleaseTitle", p_ReleaseTitle) :
                new ObjectParameter("p_ReleaseTitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("USP_RELEASE_SAVE_NON_TFS", p_SystemSeqIdParameter, p_ReleaseTitleParameter);
        }
    
        public virtual ObjectResult<string> USP_RELEASE_SAVE_RELEASE_META(Nullable<int> p_RELEASE_SEQ, Nullable<int> p_UAT_KICK_OFF, Nullable<int> p_NBR_PLAYBOOK, Nullable<int> p_NBR_ENVIRONMENT, Nullable<int> p_NBR_BUILDS, Nullable<int> p_NBR_DEPLOYMENTS, Nullable<int> p_NBR_PLAYBOOK_MEETING, Nullable<int> p_NBR_DB_REFRESH, Nullable<int> p_NBR_SECURITY_SUPPORT_HOUR, Nullable<int> p_NBR_LOAD_TEST, Nullable<int> p_NBR_BATCH_VOLUME_TEST, Nullable<int> p_NBR_SECURITY_TEST, Nullable<int> p_NBR_DESIGN_SESSION, Nullable<int> p_NBR_ARCHITECTURE_REVIEW, Nullable<int> p_TFS_RELEASE_ID, string p_RELEASE_TITLE)
        {
            var p_RELEASE_SEQParameter = p_RELEASE_SEQ.HasValue ?
                new ObjectParameter("p_RELEASE_SEQ", p_RELEASE_SEQ) :
                new ObjectParameter("p_RELEASE_SEQ", typeof(int));
    
            var p_UAT_KICK_OFFParameter = p_UAT_KICK_OFF.HasValue ?
                new ObjectParameter("p_UAT_KICK_OFF", p_UAT_KICK_OFF) :
                new ObjectParameter("p_UAT_KICK_OFF", typeof(int));
    
            var p_NBR_PLAYBOOKParameter = p_NBR_PLAYBOOK.HasValue ?
                new ObjectParameter("p_NBR_PLAYBOOK", p_NBR_PLAYBOOK) :
                new ObjectParameter("p_NBR_PLAYBOOK", typeof(int));
    
            var p_NBR_ENVIRONMENTParameter = p_NBR_ENVIRONMENT.HasValue ?
                new ObjectParameter("p_NBR_ENVIRONMENT", p_NBR_ENVIRONMENT) :
                new ObjectParameter("p_NBR_ENVIRONMENT", typeof(int));
    
            var p_NBR_BUILDSParameter = p_NBR_BUILDS.HasValue ?
                new ObjectParameter("p_NBR_BUILDS", p_NBR_BUILDS) :
                new ObjectParameter("p_NBR_BUILDS", typeof(int));
    
            var p_NBR_DEPLOYMENTSParameter = p_NBR_DEPLOYMENTS.HasValue ?
                new ObjectParameter("p_NBR_DEPLOYMENTS", p_NBR_DEPLOYMENTS) :
                new ObjectParameter("p_NBR_DEPLOYMENTS", typeof(int));
    
            var p_NBR_PLAYBOOK_MEETINGParameter = p_NBR_PLAYBOOK_MEETING.HasValue ?
                new ObjectParameter("p_NBR_PLAYBOOK_MEETING", p_NBR_PLAYBOOK_MEETING) :
                new ObjectParameter("p_NBR_PLAYBOOK_MEETING", typeof(int));
    
            var p_NBR_DB_REFRESHParameter = p_NBR_DB_REFRESH.HasValue ?
                new ObjectParameter("p_NBR_DB_REFRESH", p_NBR_DB_REFRESH) :
                new ObjectParameter("p_NBR_DB_REFRESH", typeof(int));
    
            var p_NBR_SECURITY_SUPPORT_HOURParameter = p_NBR_SECURITY_SUPPORT_HOUR.HasValue ?
                new ObjectParameter("p_NBR_SECURITY_SUPPORT_HOUR", p_NBR_SECURITY_SUPPORT_HOUR) :
                new ObjectParameter("p_NBR_SECURITY_SUPPORT_HOUR", typeof(int));
    
            var p_NBR_LOAD_TESTParameter = p_NBR_LOAD_TEST.HasValue ?
                new ObjectParameter("p_NBR_LOAD_TEST", p_NBR_LOAD_TEST) :
                new ObjectParameter("p_NBR_LOAD_TEST", typeof(int));
    
            var p_NBR_BATCH_VOLUME_TESTParameter = p_NBR_BATCH_VOLUME_TEST.HasValue ?
                new ObjectParameter("p_NBR_BATCH_VOLUME_TEST", p_NBR_BATCH_VOLUME_TEST) :
                new ObjectParameter("p_NBR_BATCH_VOLUME_TEST", typeof(int));
    
            var p_NBR_SECURITY_TESTParameter = p_NBR_SECURITY_TEST.HasValue ?
                new ObjectParameter("p_NBR_SECURITY_TEST", p_NBR_SECURITY_TEST) :
                new ObjectParameter("p_NBR_SECURITY_TEST", typeof(int));
    
            var p_NBR_DESIGN_SESSIONParameter = p_NBR_DESIGN_SESSION.HasValue ?
                new ObjectParameter("p_NBR_DESIGN_SESSION", p_NBR_DESIGN_SESSION) :
                new ObjectParameter("p_NBR_DESIGN_SESSION", typeof(int));
    
            var p_NBR_ARCHITECTURE_REVIEWParameter = p_NBR_ARCHITECTURE_REVIEW.HasValue ?
                new ObjectParameter("p_NBR_ARCHITECTURE_REVIEW", p_NBR_ARCHITECTURE_REVIEW) :
                new ObjectParameter("p_NBR_ARCHITECTURE_REVIEW", typeof(int));
    
            var p_TFS_RELEASE_IDParameter = p_TFS_RELEASE_ID.HasValue ?
                new ObjectParameter("p_TFS_RELEASE_ID", p_TFS_RELEASE_ID) :
                new ObjectParameter("p_TFS_RELEASE_ID", typeof(int));
    
            var p_RELEASE_TITLEParameter = p_RELEASE_TITLE != null ?
                new ObjectParameter("p_RELEASE_TITLE", p_RELEASE_TITLE) :
                new ObjectParameter("p_RELEASE_TITLE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_RELEASE_SAVE_RELEASE_META", p_RELEASE_SEQParameter, p_UAT_KICK_OFFParameter, p_NBR_PLAYBOOKParameter, p_NBR_ENVIRONMENTParameter, p_NBR_BUILDSParameter, p_NBR_DEPLOYMENTSParameter, p_NBR_PLAYBOOK_MEETINGParameter, p_NBR_DB_REFRESHParameter, p_NBR_SECURITY_SUPPORT_HOURParameter, p_NBR_LOAD_TESTParameter, p_NBR_BATCH_VOLUME_TESTParameter, p_NBR_SECURITY_TESTParameter, p_NBR_DESIGN_SESSIONParameter, p_NBR_ARCHITECTURE_REVIEWParameter, p_TFS_RELEASE_IDParameter, p_RELEASE_TITLEParameter);
        }
    
        public virtual int USP_SAVE_ITEM_HOURS(Nullable<long> id, Nullable<double> dev_hours, Nullable<double> des_hours, Nullable<double> total_hours)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(long));
    
            var dev_hoursParameter = dev_hours.HasValue ?
                new ObjectParameter("dev_hours", dev_hours) :
                new ObjectParameter("dev_hours", typeof(double));
    
            var des_hoursParameter = des_hours.HasValue ?
                new ObjectParameter("des_hours", des_hours) :
                new ObjectParameter("des_hours", typeof(double));
    
            var total_hoursParameter = total_hours.HasValue ?
                new ObjectParameter("total_hours", total_hours) :
                new ObjectParameter("total_hours", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_SAVE_ITEM_HOURS", idParameter, dev_hoursParameter, des_hoursParameter, total_hoursParameter);
        }
    
        public virtual int USP_SAVE_WORK_ITEM_RELEASE(Nullable<int> p_WorkItemID, Nullable<int> p_ReleaseID)
        {
            var p_WorkItemIDParameter = p_WorkItemID.HasValue ?
                new ObjectParameter("p_WorkItemID", p_WorkItemID) :
                new ObjectParameter("p_WorkItemID", typeof(int));
    
            var p_ReleaseIDParameter = p_ReleaseID.HasValue ?
                new ObjectParameter("p_ReleaseID", p_ReleaseID) :
                new ObjectParameter("p_ReleaseID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_SAVE_WORK_ITEM_RELEASE", p_WorkItemIDParameter, p_ReleaseIDParameter);
        }
    
        public virtual ObjectResult<USP_SYSTEM_GET_RECORD_Result> USP_SYSTEM_GET_RECORD(Nullable<int> system_id)
        {
            var system_idParameter = system_id.HasValue ?
                new ObjectParameter("system_id", system_id) :
                new ObjectParameter("system_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_SYSTEM_GET_RECORD_Result>("USP_SYSTEM_GET_RECORD", system_idParameter);
        }
    
        public virtual ObjectResult<USP_TABLEHELP_GET_REF_GROUP_Result> USP_TABLEHELP_GET_REF_GROUP(string p_groupCde)
        {
            var p_groupCdeParameter = p_groupCde != null ?
                new ObjectParameter("p_groupCde", p_groupCde) :
                new ObjectParameter("p_groupCde", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_TABLEHELP_GET_REF_GROUP_Result>("USP_TABLEHELP_GET_REF_GROUP", p_groupCdeParameter);
        }
    
        public virtual ObjectResult<USP_TABLEHELP_GET_REF_VALUES_Result> USP_TABLEHELP_GET_REF_VALUES(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_TABLEHELP_GET_REF_VALUES_Result>("USP_TABLEHELP_GET_REF_VALUES", idParameter);
        }
    
        public virtual ObjectResult<Nullable<long>> USP_TABLEHELP_GET_REFSEQ(string p_entityText)
        {
            var p_entityTextParameter = p_entityText != null ?
                new ObjectParameter("p_entityText", p_entityText) :
                new ObjectParameter("p_entityText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("USP_TABLEHELP_GET_REFSEQ", p_entityTextParameter);
        }
    
        public virtual ObjectResult<string> USP_TABLEHELP_GET_REFVALUE(Nullable<long> p_refSeq)
        {
            var p_refSeqParameter = p_refSeq.HasValue ?
                new ObjectParameter("p_refSeq", p_refSeq) :
                new ObjectParameter("p_refSeq", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_TABLEHELP_GET_REFVALUE", p_refSeqParameter);
        }
    
        public virtual ObjectResult<string> USP_TABLEHELP_GET_SYSTEMNAME(Nullable<long> p_systemSeq)
        {
            var p_systemSeqParameter = p_systemSeq.HasValue ?
                new ObjectParameter("p_systemSeq", p_systemSeq) :
                new ObjectParameter("p_systemSeq", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_TABLEHELP_GET_SYSTEMNAME", p_systemSeqParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> USP_TABLEHELP_GET_TFSID(Nullable<long> p_workItemSeq)
        {
            var p_workItemSeqParameter = p_workItemSeq.HasValue ?
                new ObjectParameter("p_workItemSeq", p_workItemSeq) :
                new ObjectParameter("p_workItemSeq", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("USP_TABLEHELP_GET_TFSID", p_workItemSeqParameter);
        }
    
        public virtual ObjectResult<string> USP_TABLEHELP_GET_TFSID_SYSTEM(Nullable<long> p_systemSeq)
        {
            var p_systemSeqParameter = p_systemSeq.HasValue ?
                new ObjectParameter("p_systemSeq", p_systemSeq) :
                new ObjectParameter("p_systemSeq", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_TABLEHELP_GET_TFSID_SYSTEM", p_systemSeqParameter);
        }
    
        public virtual ObjectResult<string> USP_TABLEHELP_GET_USERNAME(Nullable<long> p_userSeq)
        {
            var p_userSeqParameter = p_userSeq.HasValue ?
                new ObjectParameter("p_userSeq", p_userSeq) :
                new ObjectParameter("p_userSeq", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_TABLEHELP_GET_USERNAME", p_userSeqParameter);
        }
    
        public virtual int USP_UPDATE_ITEM_COMPONENTS(Nullable<long> component_seq, string name, Nullable<long> type, Nullable<long> complexity)
        {
            var component_seqParameter = component_seq.HasValue ?
                new ObjectParameter("component_seq", component_seq) :
                new ObjectParameter("component_seq", typeof(long));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var typeParameter = type.HasValue ?
                new ObjectParameter("type", type) :
                new ObjectParameter("type", typeof(long));
    
            var complexityParameter = complexity.HasValue ?
                new ObjectParameter("complexity", complexity) :
                new ObjectParameter("complexity", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_UPDATE_ITEM_COMPONENTS", component_seqParameter, nameParameter, typeParameter, complexityParameter);
        }
    
        public virtual ObjectResult<string> USP_USER_DELETE_DATA(string p_userName, Nullable<int> p_sysID)
        {
            var p_userNameParameter = p_userName != null ?
                new ObjectParameter("p_userName", p_userName) :
                new ObjectParameter("p_userName", typeof(string));
    
            var p_sysIDParameter = p_sysID.HasValue ?
                new ObjectParameter("p_sysID", p_sysID) :
                new ObjectParameter("p_sysID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("USP_USER_DELETE_DATA", p_userNameParameter, p_sysIDParameter);
        }
    
        public virtual ObjectResult<USP_USER_GET_DATA_Result> USP_USER_GET_DATA(string p_userName)
        {
            var p_userNameParameter = p_userName != null ?
                new ObjectParameter("p_userName", p_userName) :
                new ObjectParameter("p_userName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_USER_GET_DATA_Result>("USP_USER_GET_DATA", p_userNameParameter);
        }
    
        public virtual ObjectResult<USP_USER_GET_PROJECT_LIST_Result> USP_USER_GET_PROJECT_LIST(Nullable<int> p_systemID)
        {
            var p_systemIDParameter = p_systemID.HasValue ?
                new ObjectParameter("p_systemID", p_systemID) :
                new ObjectParameter("p_systemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_USER_GET_PROJECT_LIST_Result>("USP_USER_GET_PROJECT_LIST", p_systemIDParameter);
        }
    
        public virtual ObjectResult<USP_USER_GET_SEARCH_ITEMS_Result> USP_USER_GET_SEARCH_ITEMS(Nullable<long> p_userSeq, Nullable<long> p_sysSeq, Nullable<long> p_releaseSeq, Nullable<long> p_statusSeq, string p_itemType, Nullable<System.DateTime> p_startDte, Nullable<System.DateTime> p_endDte)
        {
            var p_userSeqParameter = p_userSeq.HasValue ?
                new ObjectParameter("p_userSeq", p_userSeq) :
                new ObjectParameter("p_userSeq", typeof(long));
    
            var p_sysSeqParameter = p_sysSeq.HasValue ?
                new ObjectParameter("p_sysSeq", p_sysSeq) :
                new ObjectParameter("p_sysSeq", typeof(long));
    
            var p_releaseSeqParameter = p_releaseSeq.HasValue ?
                new ObjectParameter("p_releaseSeq", p_releaseSeq) :
                new ObjectParameter("p_releaseSeq", typeof(long));
    
            var p_statusSeqParameter = p_statusSeq.HasValue ?
                new ObjectParameter("p_statusSeq", p_statusSeq) :
                new ObjectParameter("p_statusSeq", typeof(long));
    
            var p_itemTypeParameter = p_itemType != null ?
                new ObjectParameter("p_itemType", p_itemType) :
                new ObjectParameter("p_itemType", typeof(string));
    
            var p_startDteParameter = p_startDte.HasValue ?
                new ObjectParameter("p_startDte", p_startDte) :
                new ObjectParameter("p_startDte", typeof(System.DateTime));
    
            var p_endDteParameter = p_endDte.HasValue ?
                new ObjectParameter("p_endDte", p_endDte) :
                new ObjectParameter("p_endDte", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_USER_GET_SEARCH_ITEMS_Result>("USP_USER_GET_SEARCH_ITEMS", p_userSeqParameter, p_sysSeqParameter, p_releaseSeqParameter, p_statusSeqParameter, p_itemTypeParameter, p_startDteParameter, p_endDteParameter);
        }
    
        public virtual ObjectResult<USP_USER_GET_USER_ITEMS_Result> USP_USER_GET_USER_ITEMS(Nullable<long> p_userSeq)
        {
            var p_userSeqParameter = p_userSeq.HasValue ?
                new ObjectParameter("p_userSeq", p_userSeq) :
                new ObjectParameter("p_userSeq", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_USER_GET_USER_ITEMS_Result>("USP_USER_GET_USER_ITEMS", p_userSeqParameter);
        }
    
        public virtual ObjectResult<USP_USER_GET_USER_LIST_Result> USP_USER_GET_USER_LIST(Nullable<int> p_systemID)
        {
            var p_systemIDParameter = p_systemID.HasValue ?
                new ObjectParameter("p_systemID", p_systemID) :
                new ObjectParameter("p_systemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_USER_GET_USER_LIST_Result>("USP_USER_GET_USER_LIST", p_systemIDParameter);
        }
    
        public virtual int USP_USER_SAVE_DATA(string p_userName, Nullable<int> p_userRole, Nullable<int> p_userSystemID)
        {
            var p_userNameParameter = p_userName != null ?
                new ObjectParameter("p_userName", p_userName) :
                new ObjectParameter("p_userName", typeof(string));
    
            var p_userRoleParameter = p_userRole.HasValue ?
                new ObjectParameter("p_userRole", p_userRole) :
                new ObjectParameter("p_userRole", typeof(int));
    
            var p_userSystemIDParameter = p_userSystemID.HasValue ?
                new ObjectParameter("p_userSystemID", p_userSystemID) :
                new ObjectParameter("p_userSystemID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_USER_SAVE_DATA", p_userNameParameter, p_userRoleParameter, p_userSystemIDParameter);
        }
    
        public virtual int USP_USER_SAVE_USER_ASSIGNMENT(Nullable<long> p_ItemID, Nullable<long> p_userID, Nullable<System.DateTime> p_dueDate, string p_updtd_by)
        {
            var p_ItemIDParameter = p_ItemID.HasValue ?
                new ObjectParameter("p_ItemID", p_ItemID) :
                new ObjectParameter("p_ItemID", typeof(long));
    
            var p_userIDParameter = p_userID.HasValue ?
                new ObjectParameter("p_userID", p_userID) :
                new ObjectParameter("p_userID", typeof(long));
    
            var p_dueDateParameter = p_dueDate.HasValue ?
                new ObjectParameter("p_dueDate", p_dueDate) :
                new ObjectParameter("p_dueDate", typeof(System.DateTime));
    
            var p_updtd_byParameter = p_updtd_by != null ?
                new ObjectParameter("p_updtd_by", p_updtd_by) :
                new ObjectParameter("p_updtd_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_USER_SAVE_USER_ASSIGNMENT", p_ItemIDParameter, p_userIDParameter, p_dueDateParameter, p_updtd_byParameter);
        }
    
        public virtual int USP_USER_UPDATE_DATA(string p_userName, Nullable<long> p_systemId, Nullable<long> p_role)
        {
            var p_userNameParameter = p_userName != null ?
                new ObjectParameter("p_userName", p_userName) :
                new ObjectParameter("p_userName", typeof(string));
    
            var p_systemIdParameter = p_systemId.HasValue ?
                new ObjectParameter("p_systemId", p_systemId) :
                new ObjectParameter("p_systemId", typeof(long));
    
            var p_roleParameter = p_role.HasValue ?
                new ObjectParameter("p_role", p_role) :
                new ObjectParameter("p_role", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_USER_UPDATE_DATA", p_userNameParameter, p_systemIdParameter, p_roleParameter);
        }
    
        public virtual int USP_WORK_ITEM_UPDATE_ASSIGNMENT(string name, Nullable<long> workItemId)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var workItemIdParameter = workItemId.HasValue ?
                new ObjectParameter("workItemId", workItemId) :
                new ObjectParameter("workItemId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_WORK_ITEM_UPDATE_ASSIGNMENT", nameParameter, workItemIdParameter);
        }
    }
}
