//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET.BUSINESS.DAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ASSIGNMENTS
    {
        public long ASSIGNMENT_SEQ { get; set; }
        public long WORK_ITEM_SEQ { get; set; }
        public long USER_SEQ { get; set; }
        public long STATUS_CDE { get; set; }
        public string COMMENTS { get; set; }
        public System.DateTime UPDTD_DTE { get; set; }
        public string UPDTD_BY { get; set; }
        public Nullable<System.DateTime> DUE_DTE { get; set; }
    
        public virtual T_USERS T_USERS { get; set; }
        public virtual T_WORK_ITEM T_WORK_ITEM { get; set; }
    }
}
