//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET.BUSINESS.DAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_COMPONENT
    {
        public long COMPONENT_SEQ { get; set; }
        public Nullable<long> WORK_ITEM_SEQ { get; set; }
        public string NAME { get; set; }
        public Nullable<long> TYPE { get; set; }
        public Nullable<long> COMPLEXITY { get; set; }
        public string MULTILINGUAL { get; set; }
        public Nullable<long> RELEASE_SEQ { get; set; }
    
        public virtual T_WORK_ITEM T_WORK_ITEM { get; set; }
    }
}
