//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET.BUSINESS.DAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CONFIG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_CONFIG()
        {
            this.T_CONFIG_DETAIL = new HashSet<T_CONFIG_DETAIL>();
        }
    
        public long CONFIG_SEQ { get; set; }
        public Nullable<long> SYSTEM_SEQ { get; set; }
        public string CONFIG_NAME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_CONFIG_DETAIL> T_CONFIG_DETAIL { get; set; }
        public virtual T_SYSTEM T_SYSTEM { get; set; }
    }
}
