//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET.BUSINESS.DAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CONFIG_DETAIL
    {
        public long CONFIG_DETAIL_SEQ { get; set; }
        public Nullable<long> CONFIG_SEQ { get; set; }
        public Nullable<long> COMPLEXITY { get; set; }
        public Nullable<long> TYPE { get; set; }
        public Nullable<double> WEIGHT { get; set; }
    
        public virtual T_CONFIG T_CONFIG { get; set; }
    }
}
