//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET.BUSINESS.DAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_REFERENCE
    {
        public long REFERENCE_SEQ { get; set; }
        public string GROUP_CODE { get; set; }
        public string ENTITY_TEXT { get; set; }
        public Nullable<long> ORDER_CDE { get; set; }
    }
}
