//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET.BUSINESS.DAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_SPRINT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_SPRINT()
        {
            this.T_SPRINT_USER_ACCESS = new HashSet<T_SPRINT_USER_ACCESS>();
            this.T_WORK_ITEM = new HashSet<T_WORK_ITEM>();
        }
    
        public long SPRINT_SEQ { get; set; }
        public short NBR_STORY_POINTS { get; set; }
        public string SPRINT_NAME { get; set; }
        public Nullable<long> RELEASE_SEQ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SPRINT_USER_ACCESS> T_SPRINT_USER_ACCESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_WORK_ITEM> T_WORK_ITEM { get; set; }
        public virtual T_RELEASE T_RELEASE { get; set; }
    }
}
