//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET.BUSINESS.DAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_USERS()
        {
            this.T_ASSIGNMENTS = new HashSet<T_ASSIGNMENTS>();
            this.T_RELEASE_USER_ACCESS = new HashSet<T_RELEASE_USER_ACCESS>();
            this.T_SPRINT_USER_ACCESS = new HashSet<T_SPRINT_USER_ACCESS>();
        }
    
        public long USER_SEQ { get; set; }
        public string USER_NAME { get; set; }
        public Nullable<long> SYSTEM_SEQ { get; set; }
        public Nullable<long> USER_ROLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_ASSIGNMENTS> T_ASSIGNMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_RELEASE_USER_ACCESS> T_RELEASE_USER_ACCESS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_SPRINT_USER_ACCESS> T_SPRINT_USER_ACCESS { get; set; }
    }
}
