//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MET.BUSINESS.DAL.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_WORK_COMPONENT
    {
        public string TFS_WORK_ITEM_SEQ { get; set; }
        public string WORK_ITEM_SEQ { get; set; }
        public string COMPONENT_NAME { get; set; }
        public string COMPONENT_SEQ { get; set; }
        public long COMPONENT_COUNT { get; set; }
        public long WORK_COMPONENT_SEQ { get; set; }
        public string UPDTD_BY { get; set; }
        public Nullable<System.DateTime> UPDTD_DTE { get; set; }
    }
}
